spring.application.name=gateway
server.port=8080

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#Gateway-debug
logging.level.org.springframework.cloud.gateway=DEBUG

#Enrutamientos

#Perfil
spring.cloud.gateway.server.webflux.routes[0].id=perfil-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://perfil
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/jugadores/**,/api/v1/roles/**,/api/v1/facciones/**,/api/v1/jugador-faccion/**

#Cartacatalogo
spring.cloud.gateway.server.webflux.routes[1].id=cartacatalogo-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://cartacatalogo
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/cartas/**

#Billetera
spring.cloud.gateway.server.webflux.routes[2].id=billetera-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://billetera
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/carteras/**,/api/v1/movimientos/**

#Inventario
spring.cloud.gateway.server.webflux.routes[3].id=inventario-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://inventario
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/inventarios/**,/api/v1/inventario/**

#Mazo
spring.cloud.gateway.server.webflux.routes[4].id=mazo-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://mazo
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/mazos/**

#Rango
spring.cloud.gateway.server.webflux.routes[5].id=rango-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://rango
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/ranking/**

#Partida
spring.cloud.gateway.server.webflux.routes[6].id=partida-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://partida
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/partidas/**

#Publicacion
spring.cloud.gateway.server.webflux.routes[7].id=publicacion-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://publicacion
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/publicaciones/**,/api/v1/transacciones/**

#Compra
spring.cloud.gateway.server.webflux.routes[8].id=compra-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://compra
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/v1/suministros/**,/api/v1/aperturas/**

#Logros
spring.cloud.gateway.server.webflux.routes[9].id=logros-service
spring.cloud.gateway.server.webflux.routes[9].uri=lb://logros
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/v1/logros/**,/api/v1/logros-jugador/**